### PR TITLE
use non-blocking random and other fixes

### PR DESCRIPTION
**Pull request by rany0**
* cases of $HOME with spaces
* use urandom to prevent blocking

### CODE REVIEW

**Comment by Chexier** [comment]
Weird but ok. This script was just a joke that I made.

**Comment by rany0** [comment]
This pull was a joke too ;P

**Comment by rany0** [comment]
I came here from the ungoogled-chromium binaries for arch

**Comment by Chexier** [comment]
> This pull was a joke too ;P

Yeah ;).

> I came here from the ungoogled-chromium binaries for arch

Thanks. I'm not using Arch right now so I can't update the binares (lol).

**Pull request merged**
